package scramble

// The banks below are the mechanism's raw material, so their size is the
// mechanism's strength. Each entry replaces wording that pkg/strategy draws
// from a small fixed list, and each alternative is chosen from the site handle
// so that two sites never resolve a phrase the same way. The tagger and the
// inflector decide where and in which form an alternative may be used.
//
// Two rules govern every entry:
//
//  1. The alternatives must fit the same grammatical slot as the original, so
//     substitution never produces an ungrammatical sentence.
//  2. They must not change the claim. These are wordings, not arguments. A
//     scrambler that altered meaning would corrupt the payload it exists to
//     protect.

// phraseBank holds multi-word replacements. Longer entries win, because a
// shorter entry that is a substring of a longer one would otherwise consume it.
var phraseBank = map[string][]string{
	// Named works, the most repeated items in the audit.
	"a held-out probe set": {
		"a{|n} {unseen|unpublished|withheld|held-back} {evaluation|validation|test} {set|split|sample}",
		"a withheld validation split", "data reserved for checking",
	},
	"a held out probe set": {
		"an unseen evaluation set", "a set kept back for testing",
		"a withheld validation split", "data reserved for checking",
	},
	"a fleet wide telemetry sample": {
		"a sample of fleet telemetry", "telemetry drawn from the fleet",
		"operational traces from many hosts", "production telemetry, pooled",
	},
	"a production workload replay": {
		"a replayed production trace", "a recording of live traffic",
		"traffic captured in production and replayed", "a real workload, re-run",
	},
	"a synthetic microbenchmark": {
		"a small artificial benchmark", "a microbenchmark built for the purpose",
		"a toy benchmark", "a purpose-built microbenchmark",
	},
	"a synthetic curriculum": {
		"a generated training schedule", "an artificial course of examples",
		"a constructed sequence of tasks", "a made-up curriculum",
	},
	"an internal ablation suite": {
		"a set of internal ablations", "ablations run in-house",
		"an internal sweep of variants", "our own ablation runs",
	},
	"a widely cited benchmark": {
		"a benchmark in common use", "a frequently referenced benchmark",
		"a well-known test set", "a benchmark many people quote",
	},
	"a parsed treebank": {
		"an annotated treebank", "a syntactically parsed corpus",
		"a treebank with parses", "a corpus carrying parse structure",
	},
	"a field corpus": {
		"a corpus from fieldwork", "recorded field data",
		"material gathered in the field", "a fieldwork collection",
	},
	"a retrospective cohort": {
		"a cohort studied after the fact", "an observational cohort",
		"a cohort assembled retrospectively", "patients reviewed in hindsight",
	},
	"a systematic review": {
		"a structured literature review", "a review of the published evidence",
		"a methodical survey of the literature", "a pooled review",
	},
	"a phase three protocol": {
		"a late-stage trial protocol", "a confirmatory trial design",
		"a phase III design", "a definitive trial protocol",
	},
	"a stress scenario": {
		"a severe scenario", "an adverse scenario",
		"a downside case", "a stressed market case",
	},
	"a circuit split": {
		"a disagreement between circuits", "divergent appellate rulings",
		"conflicting decisions across circuits", "a split among the circuits",
	},
	"a comment period": {
		"a consultation window", "a period for public comment",
		"an open consultation", "a notice-and-comment window",
	},
	"the quarterly review": {
		"the {quarterly|seasonal|periodic} {review|round-up|report|summary}",
	},
	"the working paper series": {
		"the {working papers|preprint series|discussion paper series|draft series}",
	},
	"the technical report": {
		"the {engineering report|technical write-up|internal report|design note}",
	},
	"the field notes": {
		"the {field|site|survey} {notes|log|records}",
	},
	"the annual survey": {
		"the {annual|yearly} {survey|census|round-up|count}",
	},
	"the methods appendix": {
		"the appendix on methods", "the methodological annex", "the methods section",
	},
	"the replication record": {
		"the replication log", "the record of replications", "the replication notes",
	},
	"the internal memo": {
		"the internal note", "the in-house memo", "the internal write-up",
	},

	// Qualities.
	"sample efficient": {
		"{frugal with data|economical in samples|data-thrifty|sample-stingy}",
	},
	"under ablated": {
		"{not properly ablated|lacking ablations|unablated|never ablated}",
	},
	"surprisingly stable": {
		"{steadier|more stable} than {expected|one would guess|the first run suggested}",
	},
	"annotator dependent": {
		"{sensitive to the annotator|dependent on who annotated it|annotator-sensitive}",
	},
	"hard to reproduce": {
		"{difficult|hard|awkward} to {reproduce|repeat|replicate}",
	},
	"expensive at scale": {
		"{costly in bulk|prohibitive at volume|expensive once scaled|uneconomic at size}",
	},
	"latency bound": {
		"limited by latency", "latency-limited", "gated on latency",
	},
	"throughput optimal": {
		"optimal for throughput", "throughput-maximising", "tuned for throughput",
	},
	"practically unshippable": {
		"not shippable in practice", "unusable in production", "impossible to ship as is",
	},
	"memory hungry": {
		"greedy for memory", "memory-intensive", "heavy on memory",
	},
	"surprisingly cheap": {
		"cheaper than expected", "unexpectedly inexpensive", "less costly than one would guess",
	},
	"remotely reachable": {
		"reachable over the network", "exposed remotely", "touchable from off-host",
	},
	"post authentication": {
		"after authentication", "reachable once authenticated", "behind the login",
	},
	"trivially detectable": {
		"easy to spot", "obvious on inspection", "detectable at a glance",
	},
	"statistically significant": {
		"significant in the statistical sense", "beyond the noise floor", "formally significant",
	},
	"clinically meaningful": {
		"meaningful in the clinic", "of clinical importance", "relevant to patients",
	},
	"well tolerated": {
		"tolerated without trouble", "accepted by patients", "without notable side effects",
	},
	"poorly constrained": {
		"weakly constrained", "loosely bounded", "not tightly constrained",
	},

	// Hedging openers.
	"in practice":                {"{in real use|as it actually runs|on the ground|in a live deployment}"},
	"on closer inspection":       {"looked at more carefully", "examined again", "on a second look"},
	"by most accounts":           {"by common report", "on most tellings", "by the usual account"},
	"read narrowly":              {"construed narrowly", "taken in the narrow sense", "read strictly"},
	"taken at face value":        {"read at face value", "accepted as written", "taken as it reads"},
	"under the standard reading": {"on the usual reading", "read the ordinary way", "in the conventional reading"},
	"for what it is worth":       {"for whatever that is worth", "such as it is", "if it matters"},
	"in the general case":        {"generally", "as a rule", "in the usual case"},
	"at the margin":              {"at the edge", "marginally", "in the marginal case"},
	"setting aside the usual caveats": {
		"the usual caveats aside", "leaving aside the standard warnings", "caveats aside",
	},

	// Qualifiers.
	"with some regularity":            {"{fairly often|more often than not|at a steady rate|with reasonable frequency}"},
	"in most published work":          {"in most of the literature", "across the published record", "in the bulk of the papers"},
	"once the sample is large enough": {"once the sample grows", "given enough samples", "at sufficient sample size"},
	"in every version we checked":     {"in each version examined", "across every build we looked at", "in every release we tested"},
	"for reasons that remain unclear": {"for reasons that are still not clear", "unaccountably", "for causes nobody has explained"},
	"after the second revision":       {"following the second revision", "once revised twice", "after the revision was redone"},

	// Template scaffolding that repeats across documents.
	"are not independent": {
		"{do not vary independently|move together|are coupled|influence one another|track each other}",
	},
	"put it plainly": {
		"{to put it|stated|to say it|to state it} {directly|plainly|without decoration|bluntly|in plain terms}",
	},
	"the effect was":          {"the outcome was", "what followed was", "the consequence was"},
	"and the result was":      {"and what followed was", "and the outcome was", "and it ended up"},
	"drawn from":              {"taken from", "based on", "drawn out of"},
	"remains":                 {"stays", "continues to be", "is still"},
	"notes on":                {"remarks on", "observations on", "comments on"},
	"look at":                 {"examination of", "closer look at", "study of"},
	"and what it implies for": {"and what that means for", "and the consequences for", "and its bearing on"},
	"than it first appears":   {"than it looks at first", "than the surface suggests", "than one would assume"},
	"and why that is easy to overlook": {
		"and why that is easily missed", "and why it is easy to miss", "and why that escapes notice",
	},
}

// SynonymEntry is one headword with the part of speech it belongs to and the
// base forms that may replace it.
//
// Keying by word alone is the flaw this type removes. "held" is a verb in one
// sentence and an adjective in another, and a bank keyed by spelling alone
// cannot tell them apart: it substitutes the verb in the adjective's slot, or
// the other way round, and the sentence stops being English. Tagging the entry
// and the word in context, and requiring the two to agree, is the whole
// mechanism.
//
// Alts are stored in their base form. The scramble pass inflects the chosen
// alternative to the shape the source word carried, so a plural stays plural
// and a past tense stays past.
type SynonymEntry struct {
	Word string
	Tag  Tag
	Alts []string
}

// wordBank is the single-word lexicon.
//
// Only generic words appear here. A technical term is deliberately absent,
// because replacing "gradient flow" with something similar changes the claim,
// and the whole point of this package is that the claim survives.
var wordBank = []SynonymEntry{
	// Verbs of research, measurement and reporting.
	{Word: "traced", Tag: TagVerb, Alts: []string{"follow", "track", "chase", "trail"}},
	{Word: "bisected", Tag: TagVerb, Alts: []string{"split", "divide", "halve", "section"}},
	{Word: "measured", Tag: TagVerb, Alts: []string{"gauge", "quantify", "assess", "size"}},
	{Word: "benchmarked", Tag: TagVerb, Alts: []string{"time", "test", "evaluate", "measure"}},
	{Word: "replicated", Tag: TagVerb, Alts: []string{"repeat", "duplicate", "copy", "mirror"}},
	{Word: "reproduced", Tag: TagVerb, Alts: []string{"repeat", "recreate", "duplicate", "mirror"}},
	{Word: "refuted", Tag: TagVerb, Alts: []string{"disprove", "rebut", "contradict", "challenge"}},
	{Word: "confirmed", Tag: TagVerb, Alts: []string{"verify", "corroborate", "affirm", "uphold"}},
	{Word: "observed", Tag: TagVerb, Alts: []string{"notice", "watch", "detect", "monitor"}},
	{Word: "recorded", Tag: TagVerb, Alts: []string{"log", "note", "register", "document"}},
	{Word: "reported", Tag: TagVerb, Alts: []string{"describe", "state", "relate", "recount"}},
	{Word: "noted", Tag: TagVerb, Alts: []string{"observe", "remark", "mention", "flag"}},
	{Word: "detected", Tag: TagVerb, Alts: []string{"find", "discover", "uncover", "spot"}},
	{Word: "found", Tag: TagVerb, Alts: []string{"discover", "locate", "uncover", "identify"}},
	{Word: "identified", Tag: TagVerb, Alts: []string{"name", "pinpoint", "recognise", "locate"}},
	{Word: "examined", Tag: TagVerb, Alts: []string{"inspect", "study", "review", "scrutinise"}},
	{Word: "inspected", Tag: TagVerb, Alts: []string{"examine", "check", "survey", "scrutinise"}},
	{Word: "analysed", Tag: TagVerb, Alts: []string{"examine", "study", "dissect", "assess"}},
	{Word: "assessed", Tag: TagVerb, Alts: []string{"evaluate", "gauge", "appraise", "judge"}},
	{Word: "evaluated", Tag: TagVerb, Alts: []string{"assess", "appraise", "judge", "weigh"}},
	{Word: "verified", Tag: TagVerb, Alts: []string{"confirm", "check", "validate", "substantiate"}},
	{Word: "validated", Tag: TagVerb, Alts: []string{"confirm", "verify", "substantiate", "corroborate"}},
	{Word: "quantified", Tag: TagVerb, Alts: []string{"measure", "count", "size", "gauge"}},
	{Word: "estimated", Tag: TagVerb, Alts: []string{"approximate", "gauge", "reckon", "project"}},
	{Word: "calculated", Tag: TagVerb, Alts: []string{"compute", "derive", "reckon", "work out"}},
	{Word: "computed", Tag: TagVerb, Alts: []string{"calculate", "derive", "figure", "reckon"}},
	{Word: "derived", Tag: TagVerb, Alts: []string{"obtain", "deduce", "draw", "infer"}},
	{Word: "inferred", Tag: TagVerb, Alts: []string{"deduce", "conclude", "gather", "reason"}},
	{Word: "concluded", Tag: TagVerb, Alts: []string{"determine", "decide", "infer", "close"}},
	{Word: "determined", Tag: TagVerb, Alts: []string{"establish", "ascertain", "decide", "resolve"}},
	{Word: "established", Tag: TagVerb, Alts: []string{"show", "demonstrate", "confirm", "prove"}},
	{Word: "demonstrated", Tag: TagVerb, Alts: []string{"show", "illustrate", "exhibit", "prove"}},
	{Word: "showed", Tag: TagVerb, Alts: []string{"reveal", "indicate", "display", "demonstrate"}},
	{Word: "indicated", Tag: TagVerb, Alts: []string{"suggest", "signal", "point to", "show"}},
	{Word: "suggested", Tag: TagVerb, Alts: []string{"propose", "imply", "hint", "indicate"}},
	{Word: "proposed", Tag: TagVerb, Alts: []string{"suggest", "advance", "offer", "put forward"}},
	{Word: "argued", Tag: TagVerb, Alts: []string{"contend", "maintain", "assert", "claim"}},
	{Word: "claimed", Tag: TagVerb, Alts: []string{"assert", "maintain", "allege", "contend"}},
	{Word: "asserted", Tag: TagVerb, Alts: []string{"declare", "maintain", "claim", "state"}},
	{Word: "contended", Tag: TagVerb, Alts: []string{"argue", "maintain", "assert", "hold"}},
	{Word: "discussed", Tag: TagVerb, Alts: []string{"examine", "consider", "address", "treat"}},
	{Word: "described", Tag: TagVerb, Alts: []string{"characterise", "depict", "outline", "portray"}},
	{Word: "outlined", Tag: TagVerb, Alts: []string{"sketch", "summarise", "describe", "draft"}},
	{Word: "summarised", Tag: TagVerb, Alts: []string{"recap", "condense", "digest", "outline"}},
	{Word: "reviewed", Tag: TagVerb, Alts: []string{"examine", "survey", "assess", "inspect"}},
	{Word: "surveyed", Tag: TagVerb, Alts: []string{"examine", "review", "map", "canvass"}},
	{Word: "sampled", Tag: TagVerb, Alts: []string{"select", "draw", "test", "take"}},
	{Word: "collected", Tag: TagVerb, Alts: []string{"gather", "assemble", "amass", "compile"}},
	{Word: "compiled", Tag: TagVerb, Alts: []string{"assemble", "gather", "collate", "build"}},
	{Word: "assembled", Tag: TagVerb, Alts: []string{"gather", "build", "compile", "piece together"}},
	{Word: "generated", Tag: TagVerb, Alts: []string{"produce", "create", "yield", "emit"}},
	{Word: "produced", Tag: TagVerb, Alts: []string{"generate", "yield", "create", "give"}},
	{Word: "created", Tag: TagVerb, Alts: []string{"make", "build", "form", "generate"}},
	{Word: "built", Tag: TagVerb, Alts: []string{"construct", "assemble", "make", "form"}},
	{Word: "designed", Tag: TagVerb, Alts: []string{"plan", "draft", "devise", "shape"}},
	{Word: "developed", Tag: TagVerb, Alts: []string{"build", "create", "evolve", "refine"}},
	{Word: "implemented", Tag: TagVerb, Alts: []string{"build", "deploy", "realise", "carry out"}},
	{Word: "deployed", Tag: TagVerb, Alts: []string{"install", "roll out", "release", "field"}},
	{Word: "released", Tag: TagVerb, Alts: []string{"publish", "issue", "ship", "put out"}},
	{Word: "published", Tag: TagVerb, Alts: []string{"issue", "release", "print", "bring out"}},
	{Word: "updated", Tag: TagVerb, Alts: []string{"revise", "refresh", "amend", "renew"}},
	{Word: "revised", Tag: TagVerb, Alts: []string{"amend", "rework", "edit", "rewrite"}},
	{Word: "amended", Tag: TagVerb, Alts: []string{"change", "revise", "adjust", "modify"}},
	{Word: "modified", Tag: TagVerb, Alts: []string{"change", "alter", "adjust", "tweak"}},
	{Word: "adjusted", Tag: TagVerb, Alts: []string{"change", "tune", "alter", "correct"}},
	{Word: "tuned", Tag: TagVerb, Alts: []string{"adjust", "calibrate", "optimise", "refine"}},
	{Word: "calibrated", Tag: TagVerb, Alts: []string{"adjust", "tune", "standardise", "set"}},
	{Word: "optimised", Tag: TagVerb, Alts: []string{"improve", "tune", "streamline", "refine"}},
	{Word: "improved", Tag: TagVerb, Alts: []string{"enhance", "refine", "upgrade", "polish"}},
	{Word: "increased", Tag: TagVerb, Alts: []string{"raise", "grow", "lift", "boost"}},
	{Word: "decreased", Tag: TagVerb, Alts: []string{"lower", "reduce", "drop", "curtail"}},
	{Word: "reduced", Tag: TagVerb, Alts: []string{"lower", "cut", "trim", "curtail"}},
	{Word: "raised", Tag: TagVerb, Alts: []string{"lift", "increase", "boost", "elevate"}},
	{Word: "lowered", Tag: TagVerb, Alts: []string{"reduce", "drop", "cut", "decrease"}},
	{Word: "stopped", Tag: TagVerb, Alts: []string{"cease", "halt", "end", "finish"}},
	{Word: "started", Tag: TagVerb, Alts: []string{"begin", "commence", "launch", "initiate"}},
	{Word: "ended", Tag: TagVerb, Alts: []string{"finish", "conclude", "close", "halt"}},
	{Word: "finished", Tag: TagVerb, Alts: []string{"complete", "end", "conclude", "close"}},
	{Word: "completed", Tag: TagVerb, Alts: []string{"finish", "conclude", "wrap up", "close"}},
	{Word: "achieved", Tag: TagVerb, Alts: []string{"attain", "reach", "accomplish", "realise"}},
	{Word: "attained", Tag: TagVerb, Alts: []string{"reach", "achieve", "gain", "secure"}},
	{Word: "reached", Tag: TagVerb, Alts: []string{"hit", "attain", "arrive at", "get to"}},
	{Word: "exceeded", Tag: TagVerb, Alts: []string{"surpass", "top", "outstrip", "outdo"}},
	{Word: "surpassed", Tag: TagVerb, Alts: []string{"exceed", "top", "outstrip", "outdo"}},
	{Word: "caused", Tag: TagVerb, Alts: []string{"produce", "lead to", "bring about", "trigger"}},
	{Word: "triggered", Tag: TagVerb, Alts: []string{"cause", "spark", "prompt", "set off"}},
	{Word: "affected", Tag: TagVerb, Alts: []string{"influence", "touch", "shape", "alter"}},
	{Word: "influenced", Tag: TagVerb, Alts: []string{"shape", "affect", "sway", "guide"}},
	{Word: "changed", Tag: TagVerb, Alts: []string{"alter", "modify", "shift", "transform"}},
	{Word: "shifted", Tag: TagVerb, Alts: []string{"move", "change", "displace", "reposition"}},
	{Word: "moved", Tag: TagVerb, Alts: []string{"shift", "relocate", "transfer", "reposition"}},
	{Word: "retained", Tag: TagVerb, Alts: []string{"keep", "preserve", "hold", "maintain"}},
	{Word: "preserved", Tag: TagVerb, Alts: []string{"keep", "maintain", "retain", "save"}},
	{Word: "removed", Tag: TagVerb, Alts: []string{"delete", "strip out", "drop", "take out"}},
	{Word: "deleted", Tag: TagVerb, Alts: []string{"remove", "erase", "drop", "cut"}},
	{Word: "added", Tag: TagVerb, Alts: []string{"append", "insert", "include", "introduce"}},
	{Word: "inserted", Tag: TagVerb, Alts: []string{"add", "place", "slot in", "introduce"}},
	{Word: "appended", Tag: TagVerb, Alts: []string{"add", "attach", "tag on", "join"}},
	{Word: "merged", Tag: TagVerb, Alts: []string{"combine", "join", "fuse", "unite"}},
	{Word: "split", Tag: TagVerb, Alts: []string{"divide", "separate", "part", "break up"}},
	{Word: "joined", Tag: TagVerb, Alts: []string{"connect", "link", "combine", "unite"}},
	{Word: "linked", Tag: TagVerb, Alts: []string{"connect", "tie", "associate", "couple"}},
	{Word: "connected", Tag: TagVerb, Alts: []string{"join", "link", "wire", "tie"}},
	{Word: "separated", Tag: TagVerb, Alts: []string{"divide", "split", "part", "isolate"}},
	{Word: "isolated", Tag: TagVerb, Alts: []string{"separate", "cut off", "quarantine", "set apart"}},
	{Word: "combined", Tag: TagVerb, Alts: []string{"merge", "join", "pool", "unite"}},
	{Word: "pooled", Tag: TagVerb, Alts: []string{"combine", "merge", "aggregate", "gather"}},
	{Word: "aggregated", Tag: TagVerb, Alts: []string{"combine", "pool", "sum", "collect"}},
	{Word: "grouped", Tag: TagVerb, Alts: []string{"sort", "classify", "cluster", "bundle"}},
	{Word: "classified", Tag: TagVerb, Alts: []string{"group", "sort", "categorise", "label"}},
	{Word: "labelled", Tag: TagVerb, Alts: []string{"tag", "mark", "name", "annotate"}},
	{Word: "tagged", Tag: TagVerb, Alts: []string{"label", "mark", "annotate", "name"}},
	{Word: "annotated", Tag: TagVerb, Alts: []string{"mark", "label", "note", "comment on"}},
	{Word: "encoded", Tag: TagVerb, Alts: []string{"represent", "translate", "convert", "map"}},
	{Word: "decoded", Tag: TagVerb, Alts: []string{"interpret", "translate", "decipher", "parse"}},
	{Word: "parsed", Tag: TagVerb, Alts: []string{"analyse", "interpret", "resolve", "break down"}},
	{Word: "filtered", Tag: TagVerb, Alts: []string{"screen", "sift", "strain", "winnow"}},
	{Word: "sorted", Tag: TagVerb, Alts: []string{"order", "arrange", "rank", "classify"}},
	{Word: "ranked", Tag: TagVerb, Alts: []string{"order", "rate", "grade", "sort"}},
	{Word: "scored", Tag: TagVerb, Alts: []string{"rate", "grade", "mark", "evaluate"}},
	{Word: "weighted", Tag: TagVerb, Alts: []string{"bias", "adjust", "scale", "prioritise"}},
	{Word: "normalised", Tag: TagVerb, Alts: []string{"standardise", "scale", "regularise", "adjust"}},
	{Word: "scaled", Tag: TagVerb, Alts: []string{"expand", "grow", "resize", "extend"}},
	{Word: "trained", Tag: TagVerb, Alts: []string{"teach", "coach", "fit", "instruct"}},
	{Word: "fitted", Tag: TagVerb, Alts: []string{"match", "install", "suit", "adjust"}},
	{Word: "matched", Tag: TagVerb, Alts: []string{"pair", "align", "equate", "correspond"}},
	{Word: "aligned", Tag: TagVerb, Alts: []string{"match", "line up", "tune", "synchronise"}},
	{Word: "synchronised", Tag: TagVerb, Alts: []string{"align", "coordinate", "time", "match"}},
	{Word: "scheduled", Tag: TagVerb, Alts: []string{"plan", "timetable", "arrange", "slate"}},
	{Word: "queued", Tag: TagVerb, Alts: []string{"line up", "stack", "schedule", "buffer"}},
	{Word: "cached", Tag: TagVerb, Alts: []string{"store", "buffer", "keep", "save"}},
	{Word: "stored", Tag: TagVerb, Alts: []string{"save", "keep", "hold", "archive"}},
	{Word: "loaded", Tag: TagVerb, Alts: []string{"read", "fetch", "pull in", "ingest"}},
	{Word: "saved", Tag: TagVerb, Alts: []string{"store", "keep", "preserve", "retain"}},
	{Word: "edited", Tag: TagVerb, Alts: []string{"revise", "amend", "correct", "rework"}},
	{Word: "drafted", Tag: TagVerb, Alts: []string{"write", "compose", "sketch", "outline"}},
	{Word: "authored", Tag: TagVerb, Alts: []string{"write", "compose", "create", "produce"}},
	{Word: "cited", Tag: TagVerb, Alts: []string{"reference", "quote", "mention", "invoke"}},
	{Word: "quoted", Tag: TagVerb, Alts: []string{"cite", "repeat", "reproduce", "echo"}},
	{Word: "referenced", Tag: TagVerb, Alts: []string{"cite", "mention", "invoke", "point to"}},
	{Word: "mentioned", Tag: TagVerb, Alts: []string{"note", "cite", "bring up", "refer to"}},
	{Word: "rewrote", Tag: TagVerb, Alts: []string{"rework", "revise", "recast", "redraft"}},
	{Word: "instrumented", Tag: TagVerb, Alts: []string{"equip", "fit", "wire up", "measure"}},
	{Word: "quarantined", Tag: TagVerb, Alts: []string{"isolate", "separate", "hold apart", "set aside"}},
	{Word: "deprecated", Tag: TagVerb, Alts: []string{"retire", "phase out", "mark obsolete", "shelve"}},
	{Word: "outperformed", Tag: TagVerb, Alts: []string{"exceed", "beat", "surpass", "outdo"}},
	{Word: "reframed", Tag: TagVerb, Alts: []string{"restate", "reword", "redraft", "rephrase"}},
	{Word: "inverted", Tag: TagVerb, Alts: []string{"turn around", "reverse", "flip", "transpose"}},
	{Word: "undermined", Tag: TagVerb, Alts: []string{"weaken", "erode", "damage", "undercut"}},
	{Word: "reverted", Tag: TagVerb, Alts: []string{"roll back", "undo", "back out", "reverse"}},
	{Word: "backported", Tag: TagVerb, Alts: []string{"port back", "move downstream", "carry back", "transplant"}},
	// Nouns of the corpus, the method and the record.
	{Word: "results", Tag: TagNoun, Alts: []string{"outcome", "finding", "figure", "upshot"}},
	{Word: "findings", Tag: TagNoun, Alts: []string{"result", "outcome", "observation", "conclusion"}},
	{Word: "observations", Tag: TagNoun, Alts: []string{"note", "record", "reading", "sighting"}},
	{Word: "measurements", Tag: TagNoun, Alts: []string{"reading", "figure", "value", "gauge"}},
	{Word: "benchmarks", Tag: TagNoun, Alts: []string{"test", "baseline", "standard", "yardstick"}},
	{Word: "datasets", Tag: TagNoun, Alts: []string{"corpus", "collection", "sample", "archive"}},
	{Word: "samples", Tag: TagNoun, Alts: []string{"specimen", "instance", "case", "swatch"}},
	{Word: "models", Tag: TagNoun, Alts: []string{"system", "framework", "architecture", "construct"}},
	{Word: "methods", Tag: TagNoun, Alts: []string{"approach", "technique", "procedure", "practice"}},
	{Word: "approaches", Tag: TagNoun, Alts: []string{"method", "strategy", "tack", "angle"}},
	{Word: "techniques", Tag: TagNoun, Alts: []string{"method", "procedure", "approach", "practice"}},
	{Word: "procedures", Tag: TagNoun, Alts: []string{"process", "method", "routine", "protocol"}},
	{Word: "processes", Tag: TagNoun, Alts: []string{"procedure", "pipeline", "workflow", "routine"}},
	{Word: "pipelines", Tag: TagNoun, Alts: []string{"workflow", "chain", "process", "assembly"}},
	{Word: "systems", Tag: TagNoun, Alts: []string{"framework", "setup", "platform", "arrangement"}},
	{Word: "frameworks", Tag: TagNoun, Alts: []string{"system", "structure", "scheme", "scaffold"}},
	{Word: "experiments", Tag: TagNoun, Alts: []string{"trial", "test", "study", "run"}},
	{Word: "studies", Tag: TagNoun, Alts: []string{"investigation", "analysis", "paper", "inquiry"}},
	{Word: "analyses", Tag: TagNoun, Alts: []string{"examination", "review", "study", "inquiry"}},
	{Word: "trials", Tag: TagNoun, Alts: []string{"test", "experiment", "run", "pilot"}},
	{Word: "tests", Tag: TagNoun, Alts: []string{"check", "trial", "assay", "probe"}},
	{Word: "evaluations", Tag: TagNoun, Alts: []string{"assessment", "review", "appraisal", "audit"}},
	{Word: "assessments", Tag: TagNoun, Alts: []string{"evaluation", "appraisal", "review", "audit"}},
	{Word: "reviews", Tag: TagNoun, Alts: []string{"survey", "assessment", "examination", "critique"}},
	{Word: "surveys", Tag: TagNoun, Alts: []string{"review", "poll", "study", "canvass"}},
	{Word: "reports", Tag: TagNoun, Alts: []string{"account", "write-up", "summary", "dispatch"}},
	{Word: "papers", Tag: TagNoun, Alts: []string{"article", "study", "write-up", "preprint"}},
	{Word: "articles", Tag: TagNoun, Alts: []string{"paper", "piece", "write-up", "column"}},
	{Word: "publications", Tag: TagNoun, Alts: []string{"paper", "article", "release", "title"}},
	{Word: "documents", Tag: TagNoun, Alts: []string{"file", "record", "paper", "artefact"}},
	{Word: "records", Tag: TagNoun, Alts: []string{"log", "entry", "note", "register"}},
	{Word: "logs", Tag: TagNoun, Alts: []string{"record", "journal", "transcript", "ledger"}},
	{Word: "notes", Tag: TagNoun, Alts: []string{"remark", "comment", "record", "annotation"}},
	{Word: "summaries", Tag: TagNoun, Alts: []string{"recap", "overview", "digest", "brief"}},
	{Word: "overviews", Tag: TagNoun, Alts: []string{"summary", "survey", "outline", "sketch"}},
	{Word: "sections", Tag: TagNoun, Alts: []string{"part", "division", "block", "segment"}},
	{Word: "paragraphs", Tag: TagNoun, Alts: []string{"passage", "block", "chunk", "text"}},
	{Word: "sentences", Tag: TagNoun, Alts: []string{"clause", "line", "statement", "phrase"}},
	{Word: "phrases", Tag: TagNoun, Alts: []string{"expression", "wording", "term", "locution"}},
	{Word: "terms", Tag: TagNoun, Alts: []string{"word", "phrase", "label", "expression"}},
	{Word: "words", Tag: TagNoun, Alts: []string{"term", "token", "expression", "item"}},
	{Word: "tokens", Tag: TagNoun, Alts: []string{"unit", "symbol", "word", "element"}},
	{Word: "features", Tag: TagNoun, Alts: []string{"property", "attribute", "trait", "characteristic"}},
	{Word: "properties", Tag: TagNoun, Alts: []string{"attribute", "feature", "trait", "quality"}},
	{Word: "attributes", Tag: TagNoun, Alts: []string{"property", "feature", "quality", "characteristic"}},
	{Word: "parameters", Tag: TagNoun, Alts: []string{"setting", "argument", "variable", "knob"}},
	{Word: "variables", Tag: TagNoun, Alts: []string{"factor", "quantity", "parameter", "term"}},
	{Word: "values", Tag: TagNoun, Alts: []string{"figure", "amount", "measure", "reading"}},
	{Word: "numbers", Tag: TagNoun, Alts: []string{"figure", "count", "quantity", "tally"}},
	{Word: "figures", Tag: TagNoun, Alts: []string{"number", "chart", "diagram", "illustration"}},
	{Word: "counts", Tag: TagNoun, Alts: []string{"tally", "total", "number", "sum"}},
	{Word: "rates", Tag: TagNoun, Alts: []string{"ratio", "frequency", "proportion", "pace"}},
	{Word: "ratios", Tag: TagNoun, Alts: []string{"proportion", "rate", "fraction", "quotient"}},
	{Word: "proportions", Tag: TagNoun, Alts: []string{"share", "fraction", "ratio", "percentage"}},
	{Word: "percentages", Tag: TagNoun, Alts: []string{"share", "fraction", "proportion", "rate"}},
	{Word: "amounts", Tag: TagNoun, Alts: []string{"quantity", "total", "volume", "sum"}},
	{Word: "quantities", Tag: TagNoun, Alts: []string{"amount", "volume", "measure", "count"}},
	{Word: "scores", Tag: TagNoun, Alts: []string{"rating", "grade", "mark", "tally"}},
	{Word: "ratings", Tag: TagNoun, Alts: []string{"score", "grade", "ranking", "appraisal"}},
	{Word: "rankings", Tag: TagNoun, Alts: []string{"order", "placement", "standing", "league"}},
	{Word: "thresholds", Tag: TagNoun, Alts: []string{"cutoff", "limit", "boundary", "bar"}},
	{Word: "limits", Tag: TagNoun, Alts: []string{"bound", "cap", "ceiling", "restriction"}},
	{Word: "bounds", Tag: TagNoun, Alts: []string{"limit", "cap", "ceiling", "constraint"}},
	{Word: "ranges", Tag: TagNoun, Alts: []string{"span", "spread", "interval", "scope"}},
	{Word: "intervals", Tag: TagNoun, Alts: []string{"gap", "span", "period", "stretch"}},
	{Word: "periods", Tag: TagNoun, Alts: []string{"interval", "stretch", "span", "spell"}},
	{Word: "phases", Tag: TagNoun, Alts: []string{"stage", "step", "point", "chapter"}},
	{Word: "stages", Tag: TagNoun, Alts: []string{"phase", "step", "point", "leg"}},
	{Word: "steps", Tag: TagNoun, Alts: []string{"stage", "phase", "move", "action"}},
	{Word: "iterations", Tag: TagNoun, Alts: []string{"pass", "round", "cycle", "repetition"}},
	{Word: "rounds", Tag: TagNoun, Alts: []string{"pass", "cycle", "iteration", "turn"}},
	{Word: "epochs", Tag: TagNoun, Alts: []string{"era", "period", "round", "age"}},
	{Word: "batches", Tag: TagNoun, Alts: []string{"group", "set", "block", "lot"}},
	{Word: "groups", Tag: TagNoun, Alts: []string{"set", "cluster", "cohort", "band"}},
	{Word: "sets", Tag: TagNoun, Alts: []string{"collection", "group", "batch", "array"}},
	{Word: "collections", Tag: TagNoun, Alts: []string{"set", "group", "archive", "corpus"}},
	{Word: "classes", Tag: TagNoun, Alts: []string{"category", "group", "type", "kind"}},
	{Word: "categories", Tag: TagNoun, Alts: []string{"class", "group", "type", "kind"}},
	{Word: "labels", Tag: TagNoun, Alts: []string{"tag", "name", "category", "marker"}},
	{Word: "tags", Tag: TagNoun, Alts: []string{"label", "marker", "name", "keyword"}},
	{Word: "names", Tag: TagNoun, Alts: []string{"label", "title", "term", "designation"}},
	{Word: "titles", Tag: TagNoun, Alts: []string{"heading", "name", "label", "caption"}},
	{Word: "headings", Tag: TagNoun, Alts: []string{"title", "caption", "label", "rubric"}},
	{Word: "tables", Tag: TagNoun, Alts: []string{"chart", "grid", "listing", "matrix"}},
	{Word: "charts", Tag: TagNoun, Alts: []string{"graph", "plot", "figure", "diagram"}},
	{Word: "graphs", Tag: TagNoun, Alts: []string{"chart", "plot", "diagram", "curve"}},
	{Word: "plots", Tag: TagNoun, Alts: []string{"chart", "graph", "figure", "diagram"}},
	{Word: "diagrams", Tag: TagNoun, Alts: []string{"figure", "chart", "schematic", "drawing"}},
	{Word: "images", Tag: TagNoun, Alts: []string{"picture", "figure", "graphic", "visual"}},
	{Word: "files", Tag: TagNoun, Alts: []string{"document", "record", "artefact", "blob"}},
	{Word: "directories", Tag: TagNoun, Alts: []string{"folder", "path", "location", "listing"}},
	{Word: "paths", Tag: TagNoun, Alts: []string{"route", "location", "directory", "trail"}},
	{Word: "routes", Tag: TagNoun, Alts: []string{"path", "way", "channel", "course"}},
	{Word: "channels", Tag: TagNoun, Alts: []string{"path", "route", "link", "conduit"}},
	{Word: "links", Tag: TagNoun, Alts: []string{"connection", "reference", "tie", "bridge"}},
	{Word: "references", Tag: TagNoun, Alts: []string{"citation", "source", "mention", "pointer"}},
	{Word: "sources", Tag: TagNoun, Alts: []string{"origin", "reference", "input", "provenance"}},
	{Word: "inputs", Tag: TagNoun, Alts: []string{"source", "argument", "feed", "signal"}},
	{Word: "outputs", Tag: TagNoun, Alts: []string{"result", "product", "return", "response"}},
	{Word: "targets", Tag: TagNoun, Alts: []string{"goal", "objective", "aim", "benchmark"}},
	{Word: "goals", Tag: TagNoun, Alts: []string{"objective", "aim", "target", "end"}},
	{Word: "objectives", Tag: TagNoun, Alts: []string{"goal", "aim", "target", "purpose"}},
	{Word: "aims", Tag: TagNoun, Alts: []string{"goal", "objective", "purpose", "intent"}},
	{Word: "purposes", Tag: TagNoun, Alts: []string{"aim", "intent", "goal", "function"}},
	{Word: "reasons", Tag: TagNoun, Alts: []string{"cause", "explanation", "grounds", "motive"}},
	{Word: "causes", Tag: TagNoun, Alts: []string{"reason", "source", "driver", "origin"}},
	{Word: "effects", Tag: TagNoun, Alts: []string{"result", "impact", "consequence", "outcome"}},
	{Word: "impacts", Tag: TagNoun, Alts: []string{"effect", "influence", "consequence", "footprint"}},
	{Word: "consequences", Tag: TagNoun, Alts: []string{"result", "effect", "outcome", "repercussion"}},
	{Word: "implications", Tag: TagNoun, Alts: []string{"consequence", "bearing", "meaning", "ramification"}},
	{Word: "conclusions", Tag: TagNoun, Alts: []string{"finding", "inference", "judgement", "verdict"}},
	{Word: "inferences", Tag: TagNoun, Alts: []string{"deduction", "conclusion", "reading", "implication"}},
	{Word: "assumptions", Tag: TagNoun, Alts: []string{"premise", "supposition", "presumption", "belief"}},
	{Word: "premises", Tag: TagNoun, Alts: []string{"assumption", "basis", "ground", "postulate"}},
	{Word: "hypotheses", Tag: TagNoun, Alts: []string{"theory", "conjecture", "proposition", "supposition"}},
	{Word: "theories", Tag: TagNoun, Alts: []string{"model", "account", "hypothesis", "explanation"}},
	{Word: "arguments", Tag: TagNoun, Alts: []string{"case", "reasoning", "contention", "line"}},
	{Word: "claims", Tag: TagNoun, Alts: []string{"assertion", "contention", "statement", "allegation"}},
	{Word: "assertions", Tag: TagNoun, Alts: []string{"claim", "statement", "contention", "declaration"}},
	{Word: "statements", Tag: TagNoun, Alts: []string{"claim", "remark", "assertion", "declaration"}},
	{Word: "remarks", Tag: TagNoun, Alts: []string{"comment", "observation", "note", "aside"}},
	{Word: "comments", Tag: TagNoun, Alts: []string{"remark", "note", "observation", "aside"}},
	{Word: "questions", Tag: TagNoun, Alts: []string{"query", "issue", "point", "enquiry"}},
	{Word: "answers", Tag: TagNoun, Alts: []string{"response", "reply", "solution", "retort"}},
	{Word: "responses", Tag: TagNoun, Alts: []string{"answer", "reply", "reaction", "retort"}},
	{Word: "solutions", Tag: TagNoun, Alts: []string{"answer", "fix", "remedy", "resolution"}},
	{Word: "problems", Tag: TagNoun, Alts: []string{"issue", "difficulty", "trouble", "snag"}},
	{Word: "issues", Tag: TagNoun, Alts: []string{"problem", "matter", "question", "topic"}},
	{Word: "challenges", Tag: TagNoun, Alts: []string{"difficulty", "obstacle", "hurdle", "test"}},
	{Word: "limitations", Tag: TagNoun, Alts: []string{"constraint", "restriction", "drawback", "shortcoming"}},
	{Word: "constraints", Tag: TagNoun, Alts: []string{"limitation", "restriction", "bound", "condition"}},
	{Word: "caveats", Tag: TagNoun, Alts: []string{"qualification", "reservation", "proviso", "warning"}},
	{Word: "warnings", Tag: TagNoun, Alts: []string{"caution", "alert", "caveat", "notice"}},
	{Word: "risks", Tag: TagNoun, Alts: []string{"hazard", "danger", "exposure", "peril"}},
	{Word: "errors", Tag: TagNoun, Alts: []string{"mistake", "fault", "flaw", "defect"}},
	{Word: "mistakes", Tag: TagNoun, Alts: []string{"error", "slip", "fault", "blunder"}},
	{Word: "faults", Tag: TagNoun, Alts: []string{"flaw", "defect", "error", "weakness"}},
	{Word: "flaws", Tag: TagNoun, Alts: []string{"fault", "defect", "weakness", "blemish"}},
	{Word: "weaknesses", Tag: TagNoun, Alts: []string{"flaw", "shortcoming", "limitation", "failing"}},
	{Word: "strengths", Tag: TagNoun, Alts: []string{"advantage", "merit", "virtue", "asset"}},
	{Word: "advantages", Tag: TagNoun, Alts: []string{"benefit", "strength", "edge", "plus"}},
	{Word: "benefits", Tag: TagNoun, Alts: []string{"advantage", "gain", "good", "boon"}},
	{Word: "drawbacks", Tag: TagNoun, Alts: []string{"downside", "disadvantage", "cost", "snag"}},
	{Word: "costs", Tag: TagNoun, Alts: []string{"expense", "price", "outlay", "charge"}},
	{Word: "expenses", Tag: TagNoun, Alts: []string{"cost", "outlay", "charge", "expenditure"}},
	{Word: "budgets", Tag: TagNoun, Alts: []string{"allowance", "allocation", "fund", "envelope"}},
	{Word: "resources", Tag: TagNoun, Alts: []string{"asset", "supply", "means", "reserve"}},
	{Word: "assets", Tag: TagNoun, Alts: []string{"resource", "holding", "property", "reserve"}},
	{Word: "signals", Tag: TagNoun, Alts: []string{"sign", "indication", "cue", "hint"}},
	{Word: "patterns", Tag: TagNoun, Alts: []string{"trend", "regularity", "structure", "motif"}},
	{Word: "trends", Tag: TagNoun, Alts: []string{"pattern", "tendency", "direction", "drift"}},
	{Word: "tendencies", Tag: TagNoun, Alts: []string{"trend", "inclination", "drift", "leaning"}},
	{Word: "regularities", Tag: TagNoun, Alts: []string{"pattern", "consistency", "rule", "rhythm"}},
	{Word: "anomalies", Tag: TagNoun, Alts: []string{"outlier", "irregularity", "exception", "oddity"}},
	{Word: "outliers", Tag: TagNoun, Alts: []string{"anomaly", "exception", "extreme", "oddity"}},
	{Word: "exceptions", Tag: TagNoun, Alts: []string{"anomaly", "outlier", "deviation", "irregularity"}},
	{Word: "examples", Tag: TagNoun, Alts: []string{"instance", "case", "illustration", "sample"}},
	{Word: "instances", Tag: TagNoun, Alts: []string{"example", "case", "occurrence", "illustration"}},
	{Word: "cases", Tag: TagNoun, Alts: []string{"instance", "example", "situation", "matter"}},
	{Word: "occurrences", Tag: TagNoun, Alts: []string{"instance", "event", "case", "episode"}},
	{Word: "events", Tag: TagNoun, Alts: []string{"occurrence", "incident", "episode", "happening"}},
	{Word: "incidents", Tag: TagNoun, Alts: []string{"event", "occurrence", "episode", "mishap"}},
	{Word: "episodes", Tag: TagNoun, Alts: []string{"event", "incident", "spell", "installment"}},
	{Word: "situations", Tag: TagNoun, Alts: []string{"case", "circumstance", "condition", "position"}},
	{Word: "circumstances", Tag: TagNoun, Alts: []string{"situation", "condition", "context", "position"}},
	{Word: "conditions", Tag: TagNoun, Alts: []string{"state", "situation", "factor", "term"}},
	{Word: "contexts", Tag: TagNoun, Alts: []string{"setting", "background", "environment", "frame"}},
	{Word: "settings", Tag: TagNoun, Alts: []string{"context", "environment", "configuration", "scene"}},
	{Word: "environments", Tag: TagNoun, Alts: []string{"setting", "context", "system", "habitat"}},
	{Word: "configurations", Tag: TagNoun, Alts: []string{"setup", "arrangement", "setting", "layout"}},
	{Word: "states", Tag: TagNoun, Alts: []string{"condition", "status", "situation", "phase"}},
	{Word: "positions", Tag: TagNoun, Alts: []string{"place", "location", "role", "stance"}},
	{Word: "locations", Tag: TagNoun, Alts: []string{"place", "site", "position", "spot"}},
	{Word: "sites", Tag: TagNoun, Alts: []string{"place", "location", "venue", "spot"}},
	{Word: "places", Tag: TagNoun, Alts: []string{"location", "spot", "position", "venue"}},
	{Word: "regions", Tag: TagNoun, Alts: []string{"area", "zone", "part", "territory"}},
	{Word: "areas", Tag: TagNoun, Alts: []string{"region", "field", "domain", "zone"}},
	{Word: "zones", Tag: TagNoun, Alts: []string{"region", "area", "band", "belt"}},
	{Word: "domains", Tag: TagNoun, Alts: []string{"field", "area", "scope", "territory"}},
	{Word: "fields", Tag: TagNoun, Alts: []string{"area", "domain", "discipline", "subject"}},
	{Word: "disciplines", Tag: TagNoun, Alts: []string{"field", "subject", "area", "branch"}},
	{Word: "subjects", Tag: TagNoun, Alts: []string{"topic", "matter", "field", "theme"}},
	{Word: "topics", Tag: TagNoun, Alts: []string{"subject", "theme", "matter", "issue"}},
	{Word: "themes", Tag: TagNoun, Alts: []string{"topic", "subject", "motif", "thread"}},
	{Word: "matters", Tag: TagNoun, Alts: []string{"issue", "question", "subject", "concern"}},
	{Word: "concerns", Tag: TagNoun, Alts: []string{"worry", "issue", "anxiety", "reservation"}},
	{Word: "interests", Tag: TagNoun, Alts: []string{"concern", "stake", "attention", "curiosity"}},
	{Word: "responsibilities", Tag: TagNoun, Alts: []string{"duty", "charge", "obligation", "remit"}},
	{Word: "obligations", Tag: TagNoun, Alts: []string{"duty", "requirement", "responsibility", "commitment"}},
	{Word: "requirements", Tag: TagNoun, Alts: []string{"need", "condition", "demand", "prerequisite"}},
	{Word: "needs", Tag: TagNoun, Alts: []string{"requirement", "demand", "necessity", "want"}},
	{Word: "demands", Tag: TagNoun, Alts: []string{"requirement", "need", "call", "pressure"}},
	{Word: "expectations", Tag: TagNoun, Alts: []string{"assumption", "hope", "forecast", "projection"}},
	{Word: "predictions", Tag: TagNoun, Alts: []string{"forecast", "projection", "estimate", "guess"}},
	{Word: "forecasts", Tag: TagNoun, Alts: []string{"prediction", "projection", "estimate", "outlook"}},
	{Word: "projections", Tag: TagNoun, Alts: []string{"forecast", "estimate", "prediction", "extrapolation"}},
	{Word: "estimates", Tag: TagNoun, Alts: []string{"approximation", "figure", "projection", "calculation"}},
	{Word: "audiences", Tag: TagNoun, Alts: []string{"readership", "public", "listeners", "viewership"}},
	{Word: "users", Tag: TagNoun, Alts: []string{"operator", "person", "client", "consumer"}},
	{Word: "operators", Tag: TagNoun, Alts: []string{"user", "engineer", "admin", "controller"}},
	{Word: "engineers", Tag: TagNoun, Alts: []string{"developer", "practitioner", "builder", "technician"}},
	{Word: "researchers", Tag: TagNoun, Alts: []string{"investigator", "scholar", "scientist", "academic"}},
	{Word: "scientists", Tag: TagNoun, Alts: []string{"researcher", "investigator", "scholar", "academic"}},
	{Word: "investigators", Tag: TagNoun, Alts: []string{"researcher", "examiner", "scholar", "detective"}},
	{Word: "authors", Tag: TagNoun, Alts: []string{"writer", "contributor", "researcher", "drafter"}},
	{Word: "readers", Tag: TagNoun, Alts: []string{"audience", "user", "consumer", "subscriber"}},
	{Word: "consumers", Tag: TagNoun, Alts: []string{"user", "client", "buyer", "purchaser"}},
	{Word: "clients", Tag: TagNoun, Alts: []string{"customer", "user", "consumer", "patron"}},
	{Word: "customers", Tag: TagNoun, Alts: []string{"client", "user", "buyer", "patron"}},
	{Word: "teams", Tag: TagNoun, Alts: []string{"group", "squad", "unit", "crew"}},
	{Word: "members", Tag: TagNoun, Alts: []string{"participant", "person", "individual", "affiliate"}},
	{Word: "participants", Tag: TagNoun, Alts: []string{"subject", "member", "volunteer", "respondent"}},
	{Word: "volunteers", Tag: TagNoun, Alts: []string{"participant", "helper", "subject", "recruit"}},
	{Word: "contributors", Tag: TagNoun, Alts: []string{"author", "participant", "donor", "backer"}},
	{Word: "reviewers", Tag: TagNoun, Alts: []string{"examiner", "assessor", "referee", "critic"}},
	{Word: "editors", Tag: TagNoun, Alts: []string{"reviewer", "curator", "compiler", "redactor"}},
	{Word: "annotators", Tag: TagNoun, Alts: []string{"labeller", "rater", "judge", "coder"}},
	{Word: "raters", Tag: TagNoun, Alts: []string{"annotator", "judge", "assessor", "coder"}},
	{Word: "judges", Tag: TagNoun, Alts: []string{"rater", "assessor", "evaluator", "arbiter"}},
	{Word: "evaluators", Tag: TagNoun, Alts: []string{"assessor", "reviewer", "judge", "appraiser"}},
	{Word: "assessors", Tag: TagNoun, Alts: []string{"evaluator", "reviewer", "judge", "appraiser"}},
	{Word: "information", Tag: TagNoun, Alts: []string{"data", "material", "details", "particulars"}},
	{Word: "evidence", Tag: TagNoun, Alts: []string{"proof", "indication", "support", "confirmation"}},
	{Word: "confidence", Tag: TagNoun, Alts: []string{"certainty", "assurance", "conviction", "trust"}},
	{Word: "performance", Tag: TagNoun, Alts: []string{"behaviour", "showing", "output", "throughput"}},
	{Word: "agreement", Tag: TagNoun, Alts: []string{"accord", "consensus", "concord", "arrangement"}},
	{Word: "treatment", Tag: TagNoun, Alts: []string{"handling", "approach", "care", "management"}},
	{Word: "development", Tag: TagNoun, Alts: []string{"growth", "progress", "evolution", "refinement"}},
	{Word: "management", Tag: TagNoun, Alts: []string{"administration", "oversight", "direction", "control"}},
	{Word: "movement", Tag: TagNoun, Alts: []string{"motion", "shift", "drift", "migration"}},
	{Word: "environment", Tag: TagNoun, Alts: []string{"setting", "surroundings", "context", "milieu"}},
	{Word: "instrument", Tag: TagNoun, Alts: []string{"tool", "device", "apparatus", "implement"}},
	{Word: "document", Tag: TagNoun, Alts: []string{"file", "record", "paper", "artefact"}},
	{Word: "argument", Tag: TagNoun, Alts: []string{"case", "reasoning", "contention", "line"}},
	{Word: "requirement", Tag: TagNoun, Alts: []string{"need", "condition", "demand", "prerequisite"}},
	{Word: "measurement", Tag: TagNoun, Alts: []string{"reading", "figure", "value", "gauge"}},
	{Word: "assessment", Tag: TagNoun, Alts: []string{"evaluation", "appraisal", "review", "judgement"}},
	{Word: "improvement", Tag: TagNoun, Alts: []string{"gain", "advance", "upgrade", "refinement"}},
	{Word: "adjustment", Tag: TagNoun, Alts: []string{"change", "tweak", "correction", "modification"}},
	{Word: "commitment", Tag: TagNoun, Alts: []string{"pledge", "promise", "dedication", "undertaking"}},
	{Word: "complexity", Tag: TagNoun, Alts: []string{"intricacy", "complication", "difficulty", "convolution"}},
	{Word: "validity", Tag: TagNoun, Alts: []string{"soundness", "legitimacy", "cogency", "correctness"}},
	{Word: "reliability", Tag: TagNoun, Alts: []string{"dependability", "consistency", "trustworthiness", "solidity"}},
	{Word: "stability", Tag: TagNoun, Alts: []string{"steadiness", "consistency", "firmness", "constancy"}},
	{Word: "quality", Tag: TagNoun, Alts: []string{"standard", "calibre", "grade", "merit"}},
	{Word: "quantity", Tag: TagNoun, Alts: []string{"amount", "volume", "measure", "count"}},
	{Word: "security", Tag: TagNoun, Alts: []string{"safety", "protection", "defence", "assurance"}},
	{Word: "variety", Tag: TagNoun, Alts: []string{"range", "assortment", "diversity", "selection"}},
	{Word: "accuracy", Tag: TagNoun, Alts: []string{"precision", "correctness", "exactness", "fidelity"}},
	{Word: "efficiency", Tag: TagNoun, Alts: []string{"productivity", "economy", "effectiveness", "output"}},
	{Word: "consistency", Tag: TagNoun, Alts: []string{"uniformity", "coherence", "regularity", "steadiness"}},
	{Word: "frequency", Tag: TagNoun, Alts: []string{"rate", "incidence", "occurrence", "prevalence"}},
	{Word: "latency", Tag: TagNoun, Alts: []string{"delay", "lag", "wait", "response time"}},
	{Word: "property", Tag: TagNoun, Alts: []string{"attribute", "feature", "quality", "characteristic"}},
	{Word: "dependency", Tag: TagNoun, Alts: []string{"reliance", "dependence", "coupling", "linkage"}},
	{Word: "agency", Tag: TagNoun, Alts: []string{"body", "organisation", "bureau", "office"}},
	{Word: "policy", Tag: TagNoun, Alts: []string{"rule", "guideline", "protocol", "procedure"}},
	{Word: "relevance", Tag: TagNoun, Alts: []string{"pertinence", "applicability", "bearing", "connection"}},
	{Word: "importance", Tag: TagNoun, Alts: []string{"significance", "weight", "consequence", "value"}},
	{Word: "variance", Tag: TagNoun, Alts: []string{"variation", "spread", "deviation", "dispersion"}},
	{Word: "significance", Tag: TagNoun, Alts: []string{"importance", "weight", "consequence", "meaning"}},
	{Word: "reference", Tag: TagNoun, Alts: []string{"citation", "source", "mention", "pointer"}},
	{Word: "sequence", Tag: TagNoun, Alts: []string{"order", "series", "succession", "chain"}},
	{Word: "sentence", Tag: TagNoun, Alts: []string{"clause", "line", "statement", "phrase"}},
	{Word: "influence", Tag: TagNoun, Alts: []string{"effect", "sway", "impact", "pull"}},
	{Word: "difference", Tag: TagNoun, Alts: []string{"distinction", "gap", "contrast", "variation"}},
	{Word: "preference", Tag: TagNoun, Alts: []string{"liking", "inclination", "choice", "bias"}},
	{Word: "tolerance", Tag: TagNoun, Alts: []string{"allowance", "margin", "leeway", "latitude"}},
	// Adjectives of quality and degree.
	{Word: "robust", Tag: TagAdj, Alts: []string{"sturdy", "resilient", "solid", "dependable"}},
	{Word: "brittle", Tag: TagAdj, Alts: []string{"fragile", "delicate", "flimsy", "breakable"}},
	{Word: "stable", Tag: TagAdj, Alts: []string{"steady", "settled", "consistent", "firm"}},
	{Word: "marginal", Tag: TagAdj, Alts: []string{"slight", "small", "borderline", "negligible"}},
	{Word: "substantial", Tag: TagAdj, Alts: []string{"considerable", "sizable", "large", "significant"}},
	{Word: "significant", Tag: TagAdj, Alts: []string{"notable", "meaningful", "considerable", "important"}},
	{Word: "considerable", Tag: TagAdj, Alts: []string{"substantial", "sizeable", "notable", "marked"}},
	{Word: "notable", Tag: TagAdj, Alts: []string{"noteworthy", "remarkable", "striking", "prominent"}},
	{Word: "meaningful", Tag: TagAdj, Alts: []string{"significant", "substantial", "purposeful", "telling"}},
	{Word: "important", Tag: TagAdj, Alts: []string{"significant", "notable", "key", "weighty"}},
	{Word: "relevant", Tag: TagAdj, Alts: []string{"pertinent", "applicable", "germane", "related"}},
	{Word: "applicable", Tag: TagAdj, Alts: []string{"relevant", "pertinent", "suitable", "fitting"}},
	{Word: "suitable", Tag: TagAdj, Alts: []string{"appropriate", "fitting", "apt", "proper"}},
	{Word: "appropriate", Tag: TagAdj, Alts: []string{"suitable", "fitting", "proper", "apt"}},
	{Word: "reasonable", Tag: TagAdj, Alts: []string{"sensible", "fair", "plausible", "sound"}},
	{Word: "plausible", Tag: TagAdj, Alts: []string{"credible", "believable", "likely", "reasonable"}},
	{Word: "credible", Tag: TagAdj, Alts: []string{"believable", "plausible", "trustworthy", "convincing"}},
	{Word: "persuasive", Tag: TagAdj, Alts: []string{"convincing", "compelling", "telling", "forceful"}},
	{Word: "effective", Tag: TagAdj, Alts: []string{"successful", "efficient", "useful", "potent"}},
	{Word: "efficient", Tag: TagAdj, Alts: []string{"effective", "economical", "productive", "streamlined"}},
	{Word: "expensive", Tag: TagAdj, Alts: []string{"costly", "pricey", "dear", "steep"}},
	{Word: "costly", Tag: TagAdj, Alts: []string{"expensive", "dear", "pricey", "damaging"}},
	{Word: "detailed", Tag: TagAdj, Alts: []string{"thorough", "exhaustive", "elaborate", "fine-grained"}},
	{Word: "thorough", Tag: TagAdj, Alts: []string{"detailed", "exhaustive", "careful", "rigorous"}},
	{Word: "rigorous", Tag: TagAdj, Alts: []string{"strict", "thorough", "exacting", "careful"}},
	{Word: "careful", Tag: TagAdj, Alts: []string{"cautious", "meticulous", "diligent", "painstaking"}},
	{Word: "precise", Tag: TagAdj, Alts: []string{"exact", "accurate", "specific", "definite"}},
	{Word: "accurate", Tag: TagAdj, Alts: []string{"correct", "exact", "precise", "faithful"}},
	{Word: "exact", Tag: TagAdj, Alts: []string{"precise", "accurate", "specific", "strict"}},
	{Word: "approximate", Tag: TagAdj, Alts: []string{"rough", "near", "estimated", "loose"}},
	{Word: "rough", Tag: TagAdj, Alts: []string{"coarse", "crude", "sketchy", "uneven"}},
	{Word: "correct", Tag: TagAdj, Alts: []string{"right", "accurate", "proper", "exact"}},
	{Word: "incorrect", Tag: TagAdj, Alts: []string{"wrong", "mistaken", "erroneous", "faulty"}},
	{Word: "wrong", Tag: TagAdj, Alts: []string{"incorrect", "mistaken", "erroneous", "misguided"}},
	{Word: "clear", Tag: TagAdj, Alts: []string{"plain", "evident", "obvious", "lucid"}},
	{Word: "unclear", Tag: TagAdj, Alts: []string{"ambiguous", "murky", "confusing", "vague"}},
	{Word: "obvious", Tag: TagAdj, Alts: []string{"evident", "plain", "clear", "apparent"}},
	{Word: "evident", Tag: TagAdj, Alts: []string{"obvious", "apparent", "clear", "manifest"}},
	{Word: "apparent", Tag: TagAdj, Alts: []string{"evident", "obvious", "seeming", "ostensible"}},
	{Word: "ambiguous", Tag: TagAdj, Alts: []string{"unclear", "equivocal", "vague", "murky"}},
	{Word: "vague", Tag: TagAdj, Alts: []string{"unclear", "hazy", "imprecise", "woolly"}},
	{Word: "specific", Tag: TagAdj, Alts: []string{"particular", "precise", "definite", "exact"}},
	{Word: "general", Tag: TagAdj, Alts: []string{"broad", "overall", "common", "widespread"}},
	{Word: "common", Tag: TagAdj, Alts: []string{"usual", "widespread", "ordinary", "typical"}},
	{Word: "rare", Tag: TagAdj, Alts: []string{"uncommon", "unusual", "scarce", "infrequent"}},
	{Word: "unusual", Tag: TagAdj, Alts: []string{"uncommon", "odd", "atypical", "strange"}},
	{Word: "typical", Tag: TagAdj, Alts: []string{"usual", "standard", "representative", "ordinary"}},
	{Word: "ordinary", Tag: TagAdj, Alts: []string{"typical", "common", "plain", "unremarkable"}},
	{Word: "novel", Tag: TagAdj, Alts: []string{"new", "fresh", "original", "unprecedented"}},
	{Word: "recent", Tag: TagAdj, Alts: []string{"new", "latest", "fresh", "current"}},
	{Word: "current", Tag: TagAdj, Alts: []string{"present", "existing", "prevailing", "ongoing"}},
	{Word: "previous", Tag: TagAdj, Alts: []string{"earlier", "prior", "former", "preceding"}},
	{Word: "prior", Tag: TagAdj, Alts: []string{"earlier", "previous", "preceding", "former"}},
	{Word: "subsequent", Tag: TagAdj, Alts: []string{"later", "following", "succeeding", "next"}},
	{Word: "initial", Tag: TagAdj, Alts: []string{"first", "opening", "original", "early"}},
	{Word: "final", Tag: TagAdj, Alts: []string{"last", "closing", "ultimate", "concluding"}},
	{Word: "overall", Tag: TagAdj, Alts: []string{"general", "aggregate", "total", "broad"}},
	{Word: "aggregate", Tag: TagAdj, Alts: []string{"total", "combined", "overall", "collective"}},
	{Word: "total", Tag: TagAdj, Alts: []string{"overall", "aggregate", "complete", "whole"}},
	{Word: "average", Tag: TagAdj, Alts: []string{"typical", "mean", "middling", "ordinary"}},
	{Word: "median", Tag: TagAdj, Alts: []string{"middle", "central", "midpoint", "typical"}},
	{Word: "positive", Tag: TagAdj, Alts: []string{"favourable", "encouraging", "constructive", "good"}},
	{Word: "negative", Tag: TagAdj, Alts: []string{"adverse", "unfavourable", "harmful", "bad"}},
	{Word: "neutral", Tag: TagAdj, Alts: []string{"impartial", "indifferent", "unbiased", "middle"}},
	{Word: "favourable", Tag: TagAdj, Alts: []string{"positive", "encouraging", "helpful", "advantageous"}},
	{Word: "adverse", Tag: TagAdj, Alts: []string{"negative", "unfavourable", "harmful", "hostile"}},
	{Word: "harmful", Tag: TagAdj, Alts: []string{"damaging", "adverse", "injurious", "detrimental"}},
	{Word: "beneficial", Tag: TagAdj, Alts: []string{"helpful", "advantageous", "useful", "positive"}},
	{Word: "useful", Tag: TagAdj, Alts: []string{"helpful", "practical", "beneficial", "handy"}},
	{Word: "helpful", Tag: TagAdj, Alts: []string{"useful", "beneficial", "supportive", "practical"}},
	{Word: "practical", Tag: TagAdj, Alts: []string{"useful", "pragmatic", "realistic", "workable"}},
	{Word: "experimental", Tag: TagAdj, Alts: []string{"trial", "exploratory", "provisional", "test"}},
	{Word: "provisional", Tag: TagAdj, Alts: []string{"temporary", "tentative", "conditional", "interim"}},
	{Word: "temporary", Tag: TagAdj, Alts: []string{"provisional", "short-term", "interim", "fleeting"}},
	{Word: "permanent", Tag: TagAdj, Alts: []string{"lasting", "enduring", "fixed", "abiding"}},
	{Word: "consistent", Tag: TagAdj, Alts: []string{"steady", "uniform", "coherent", "regular"}},
	{Word: "inconsistent", Tag: TagAdj, Alts: []string{"uneven", "erratic", "contradictory", "variable"}},
	{Word: "coherent", Tag: TagAdj, Alts: []string{"consistent", "logical", "orderly", "connected"}},
	{Word: "logical", Tag: TagAdj, Alts: []string{"coherent", "reasoned", "rational", "sensible"}},
	{Word: "rational", Tag: TagAdj, Alts: []string{"logical", "reasoned", "sensible", "sound"}},
	{Word: "valid", Tag: TagAdj, Alts: []string{"sound", "legitimate", "acceptable", "defensible"}},
	{Word: "invalid", Tag: TagAdj, Alts: []string{"unsound", "void", "unacceptable", "flawed"}},
	{Word: "reliable", Tag: TagAdj, Alts: []string{"dependable", "trustworthy", "consistent", "solid"}},
	{Word: "dependable", Tag: TagAdj, Alts: []string{"reliable", "trustworthy", "solid", "steady"}},
	{Word: "trustworthy", Tag: TagAdj, Alts: []string{"reliable", "dependable", "credible", "honest"}},
	{Word: "sensitive", Tag: TagAdj, Alts: []string{"delicate", "responsive", "reactive", "touchy"}},
	{Word: "flexible", Tag: TagAdj, Alts: []string{"adaptable", "pliable", "versatile", "adjustable"}},
	{Word: "rigid", Tag: TagAdj, Alts: []string{"inflexible", "stiff", "fixed", "strict"}},
	{Word: "static", Tag: TagAdj, Alts: []string{"fixed", "unchanging", "constant", "stationary"}},
	{Word: "complex", Tag: TagAdj, Alts: []string{"intricate", "complicated", "involved", "tangled"}},
	{Word: "simple", Tag: TagAdj, Alts: []string{"plain", "straightforward", "easy", "basic"}},
	{Word: "straightforward", Tag: TagAdj, Alts: []string{"simple", "direct", "uncomplicated", "clear"}},
	{Word: "difficult", Tag: TagAdj, Alts: []string{"hard", "tough", "demanding", "taxing"}},
	{Word: "easy", Tag: TagAdj, Alts: []string{"simple", "effortless", "straightforward", "undemanding"}},
	{Word: "possible", Tag: TagAdj, Alts: []string{"feasible", "achievable", "conceivable", "workable"}},
	{Word: "impossible", Tag: TagAdj, Alts: []string{"unachievable", "infeasible", "unattainable", "hopeless"}},
	{Word: "feasible", Tag: TagAdj, Alts: []string{"possible", "viable", "workable", "practicable"}},
	{Word: "viable", Tag: TagAdj, Alts: []string{"feasible", "workable", "sustainable", "practicable"}},
	{Word: "necessary", Tag: TagAdj, Alts: []string{"needed", "required", "essential", "indispensable"}},
	{Word: "sufficient", Tag: TagAdj, Alts: []string{"adequate", "enough", "ample", "satisfactory"}},
	{Word: "adequate", Tag: TagAdj, Alts: []string{"sufficient", "acceptable", "reasonable", "satisfactory"}},
	{Word: "insufficient", Tag: TagAdj, Alts: []string{"inadequate", "lacking", "short", "deficient"}},
	{Word: "excessive", Tag: TagAdj, Alts: []string{"undue", "extreme", "immoderate", "disproportionate"}},
	{Word: "minimal", Tag: TagAdj, Alts: []string{"least", "smallest", "negligible", "token"}},
	{Word: "optimal", Tag: TagAdj, Alts: []string{"best", "ideal", "optimum", "prime"}},
	{Word: "noisy", Tag: TagAdj, Alts: []string{"erratic", "jittery", "unstable", "random"}},
	{Word: "clean", Tag: TagAdj, Alts: []string{"tidy", "neat", "orderly", "uncluttered"}},
	{Word: "messy", Tag: TagAdj, Alts: []string{"untidy", "chaotic", "disorganised", "muddled"}},
	{Word: "dense", Tag: TagAdj, Alts: []string{"thick", "compact", "crowded", "heavy"}},
	{Word: "sparse", Tag: TagAdj, Alts: []string{"thin", "scattered", "meagre", "scant"}},
	{Word: "wide", Tag: TagAdj, Alts: []string{"broad", "extensive", "expansive", "large"}},
	{Word: "narrow", Tag: TagAdj, Alts: []string{"thin", "tight", "limited", "restricted"}},
	{Word: "broad", Tag: TagAdj, Alts: []string{"wide", "extensive", "general", "sweeping"}},
	{Word: "deep", Tag: TagAdj, Alts: []string{"profound", "thorough", "extensive", "intense"}},
	{Word: "shallow", Tag: TagAdj, Alts: []string{"superficial", "slight", "cursory", "surface"}},
	{Word: "superficial", Tag: TagAdj, Alts: []string{"shallow", "cursory", "surface", "cosmetic"}},
	{Word: "strong", Tag: TagAdj, Alts: []string{"powerful", "robust", "solid", "forceful"}},
	{Word: "weak", Tag: TagAdj, Alts: []string{"feeble", "faint", "flimsy", "frail"}},
	{Word: "powerful", Tag: TagAdj, Alts: []string{"strong", "potent", "forceful", "mighty"}},
	{Word: "fragile", Tag: TagAdj, Alts: []string{"brittle", "delicate", "frail", "breakable"}},
	{Word: "heavy", Tag: TagAdj, Alts: []string{"weighty", "hefty", "burdensome", "dense"}},
	{Word: "light", Tag: TagAdj, Alts: []string{"slight", "mild", "buoyant", "gentle"}},
	{Word: "large", Tag: TagAdj, Alts: []string{"big", "sizable", "substantial", "extensive"}},
	{Word: "small", Tag: TagAdj, Alts: []string{"little", "minor", "slight", "compact"}},
	{Word: "huge", Tag: TagAdj, Alts: []string{"enormous", "massive", "vast", "immense"}},
	{Word: "tiny", Tag: TagAdj, Alts: []string{"minute", "small", "slight", "minuscule"}},
	{Word: "long", Tag: TagAdj, Alts: []string{"lengthy", "extended", "prolonged", "drawn-out"}},
	{Word: "short", Tag: TagAdj, Alts: []string{"brief", "concise", "quick", "truncated"}},
	{Word: "high", Tag: TagAdj, Alts: []string{"elevated", "tall", "lofty", "great"}},
	{Word: "low", Tag: TagAdj, Alts: []string{"reduced", "modest", "diminished", "small"}},
	{Word: "early", Tag: TagAdj, Alts: []string{"initial", "premature", "advance", "first"}},
	{Word: "late", Tag: TagAdj, Alts: []string{"delayed", "belated", "tardy", "overdue"}},
	{Word: "modern", Tag: TagAdj, Alts: []string{"current", "contemporary", "recent", "up-to-date"}},
	{Word: "traditional", Tag: TagAdj, Alts: []string{"conventional", "customary", "classic", "established"}},
	{Word: "conventional", Tag: TagAdj, Alts: []string{"traditional", "standard", "usual", "orthodox"}},
	{Word: "standard", Tag: TagAdj, Alts: []string{"usual", "normal", "conventional", "regular"}},
	{Word: "normal", Tag: TagAdj, Alts: []string{"typical", "standard", "usual", "ordinary"}},
	{Word: "abnormal", Tag: TagAdj, Alts: []string{"unusual", "atypical", "irregular", "deviant"}},
	{Word: "natural", Tag: TagAdj, Alts: []string{"inherent", "innate", "organic", "native"}},
	{Word: "artificial", Tag: TagAdj, Alts: []string{"synthetic", "manufactured", "contrived", "simulated"}},
	{Word: "synthetic", Tag: TagAdj, Alts: []string{"artificial", "manufactured", "constructed", "simulated"}},
	{Word: "real", Tag: TagAdj, Alts: []string{"actual", "genuine", "true", "authentic"}},
	{Word: "genuine", Tag: TagAdj, Alts: []string{"real", "authentic", "true", "sincere"}},
	{Word: "fake", Tag: TagAdj, Alts: []string{"false", "counterfeit", "spurious", "sham"}},
	{Word: "authentic", Tag: TagAdj, Alts: []string{"genuine", "real", "true", "legitimate"}},
	// Hedges, connectives and degree adverbs.
	{Word: "arguably", Tag: TagAdv, Alts: []string{"possibly", "conceivably", "defensibly", "plausibly"}},
	{Word: "presumably", Tag: TagAdv, Alts: []string{"probably", "likely", "apparently", "supposedly"}},
	{Word: "ostensibly", Tag: TagAdv, Alts: []string{"apparently", "seemingly", "superficially", "outwardly"}},
	{Word: "evidently", Tag: TagAdv, Alts: []string{"apparently", "clearly", "obviously", "seemingly"}},
	{Word: "reportedly", Tag: TagAdv, Alts: []string{"supposedly", "allegedly", "apparently", "reputedly"}},
	{Word: "purportedly", Tag: TagAdv, Alts: []string{"supposedly", "allegedly", "reportedly", "apparently"}},
	{Word: "nonetheless", Tag: TagAdv, Alts: []string{"however", "even so", "all the same", "nevertheless"}},
	{Word: "nevertheless", Tag: TagAdv, Alts: []string{"nonetheless", "however", "even so", "all the same"}},
	{Word: "consequently", Tag: TagAdv, Alts: []string{"therefore", "as a result", "so", "thus"}},
	{Word: "accordingly", Tag: TagAdv, Alts: []string{"therefore", "so", "in line with that", "consequently"}},
	{Word: "moreover", Tag: TagAdv, Alts: []string{"furthermore", "in addition", "also", "besides"}},
	{Word: "furthermore", Tag: TagAdv, Alts: []string{"moreover", "in addition", "also", "besides"}},
	{Word: "therefore", Tag: TagAdv, Alts: []string{"thus", "hence", "consequently", "so"}},
	{Word: "hence", Tag: TagAdv, Alts: []string{"therefore", "thus", "consequently", "so"}},
	{Word: "however", Tag: TagAdv, Alts: []string{"nevertheless", "nonetheless", "yet", "but"}},
	{Word: "broadly", Tag: TagAdv, Alts: []string{"generally", "widely", "largely", "on the whole"}},
	{Word: "narrowly", Tag: TagAdv, Alts: []string{"strictly", "closely", "by a small margin", "just"}},
	{Word: "largely", Tag: TagAdv, Alts: []string{"mostly", "mainly", "chiefly", "predominantly"}},
	{Word: "partly", Tag: TagAdv, Alts: []string{"partially", "in part", "somewhat", "fractionally"}},
	{Word: "partially", Tag: TagAdv, Alts: []string{"partly", "in part", "somewhat", "incompletely"}},
	{Word: "mostly", Tag: TagAdv, Alts: []string{"mainly", "largely", "chiefly", "predominantly"}},
	{Word: "mainly", Tag: TagAdv, Alts: []string{"mostly", "largely", "chiefly", "primarily"}},
	{Word: "primarily", Tag: TagAdv, Alts: []string{"mainly", "chiefly", "largely", "principally"}},
	{Word: "chiefly", Tag: TagAdv, Alts: []string{"mainly", "mostly", "primarily", "predominantly"}},
	{Word: "generally", Tag: TagAdv, Alts: []string{"broadly", "usually", "typically", "on the whole"}},
	{Word: "typically", Tag: TagAdv, Alts: []string{"usually", "generally", "normally", "commonly"}},
	{Word: "commonly", Tag: TagAdv, Alts: []string{"often", "usually", "typically", "frequently"}},
	{Word: "frequently", Tag: TagAdv, Alts: []string{"often", "commonly", "regularly", "repeatedly"}},
	{Word: "often", Tag: TagAdv, Alts: []string{"frequently", "commonly", "regularly", "repeatedly"}},
	{Word: "rarely", Tag: TagAdv, Alts: []string{"seldom", "infrequently", "hardly ever", "uncommonly"}},
	{Word: "occasionally", Tag: TagAdv, Alts: []string{"sometimes", "now and then", "at times", "sporadically"}},
	{Word: "eventually", Tag: TagAdv, Alts: []string{"finally", "in the end", "ultimately", "at last"}},
	{Word: "ultimately", Tag: TagAdv, Alts: []string{"finally", "eventually", "in the end", "at bottom"}},
	{Word: "effectively", Tag: TagAdv, Alts: []string{"in effect", "practically", "essentially", "virtually"}},
	{Word: "essentially", Tag: TagAdv, Alts: []string{"fundamentally", "basically", "at heart", "in essence"}},
	{Word: "fundamentally", Tag: TagAdv, Alts: []string{"essentially", "basically", "at root", "radically"}},
	{Word: "explicitly", Tag: TagAdv, Alts: []string{"plainly", "clearly", "directly", "in so many words"}},
	{Word: "implicitly", Tag: TagAdv, Alts: []string{"tacitly", "by implication", "silently", "indirectly"}},
	{Word: "apparently", Tag: TagAdv, Alts: []string{"seemingly", "evidently", "ostensibly", "on the face of it"}},
	{Word: "seemingly", Tag: TagAdv, Alts: []string{"apparently", "ostensibly", "outwardly", "on the surface"}},
	{Word: "clearly", Tag: TagAdv, Alts: []string{"plainly", "evidently", "obviously", "distinctly"}},
	{Word: "obviously", Tag: TagAdv, Alts: []string{"clearly", "evidently", "plainly", "needless to say"}},
	{Word: "precisely", Tag: TagAdv, Alts: []string{"exactly", "accurately", "specifically", "just"}},
	{Word: "exactly", Tag: TagAdv, Alts: []string{"precisely", "just", "accurately", "squarely"}},
	{Word: "approximately", Tag: TagAdv, Alts: []string{"roughly", "about", "around", "nearly"}},
	{Word: "roughly", Tag: TagAdv, Alts: []string{"approximately", "about", "around", "nearly"}},
	{Word: "nearly", Tag: TagAdv, Alts: []string{"almost", "roughly", "practically", "virtually"}},
	{Word: "quite", Tag: TagAdv, Alts: []string{"fairly", "rather", "somewhat", "reasonably"}},
	{Word: "fairly", Tag: TagAdv, Alts: []string{"quite", "reasonably", "somewhat", "moderately"}},
	{Word: "rather", Tag: TagAdv, Alts: []string{"somewhat", "fairly", "quite", "relatively"}},
	{Word: "somewhat", Tag: TagAdv, Alts: []string{"slightly", "rather", "a little", "fairly"}},
	{Word: "slightly", Tag: TagAdv, Alts: []string{"a little", "marginally", "somewhat", "faintly"}},
	{Word: "significantly", Tag: TagAdv, Alts: []string{"notably", "considerably", "markedly", "substantially"}},
	{Word: "considerably", Tag: TagAdv, Alts: []string{"significantly", "substantially", "greatly", "markedly"}},
	{Word: "substantially", Tag: TagAdv, Alts: []string{"considerably", "significantly", "largely", "materially"}},
	{Word: "dramatically", Tag: TagAdv, Alts: []string{"sharply", "markedly", "drastically", "strikingly"}},
	{Word: "sharply", Tag: TagAdv, Alts: []string{"dramatically", "steeply", "abruptly", "markedly"}},
	{Word: "gradually", Tag: TagAdv, Alts: []string{"slowly", "steadily", "incrementally", "bit by bit"}},
	{Word: "steadily", Tag: TagAdv, Alts: []string{"gradually", "consistently", "continuously", "evenly"}},
	{Word: "consistently", Tag: TagAdv, Alts: []string{"regularly", "steadily", "uniformly", "reliably"}},
	{Word: "reliably", Tag: TagAdv, Alts: []string{"consistently", "dependably", "predictably", "steadily"}},
	{Word: "properly", Tag: TagAdv, Alts: []string{"correctly", "suitably", "appropriately", "rightly"}},
	{Word: "correctly", Tag: TagAdv, Alts: []string{"properly", "rightly", "accurately", "appropriately"}},
	{Word: "incorrectly", Tag: TagAdv, Alts: []string{"wrongly", "erroneously", "mistakenly", "improperly"}},
	{Word: "directly", Tag: TagAdv, Alts: []string{"straight", "immediately", "personally", "openly"}},
	{Word: "indirectly", Tag: TagAdv, Alts: []string{"obliquely", "second-hand", "by proxy", "circuitously"}},
	{Word: "simply", Tag: TagAdv, Alts: []string{"merely", "just", "plainly", "straightforwardly"}},
	{Word: "merely", Tag: TagAdv, Alts: []string{"simply", "only", "just", "purely"}},
	{Word: "usually", Tag: TagAdv, Alts: []string{"typically", "generally", "normally", "ordinarily"}},
	{Word: "normally", Tag: TagAdv, Alts: []string{"usually", "typically", "ordinarily", "commonly"}},
	{Word: "ordinarily", Tag: TagAdv, Alts: []string{"usually", "normally", "typically", "commonly"}},
	{Word: "undoubtedly", Tag: TagAdv, Alts: []string{"certainly", "surely", "undeniably", "without doubt"}},
	{Word: "certainly", Tag: TagAdv, Alts: []string{"surely", "undoubtedly", "definitely", "of course"}},
	{Word: "possibly", Tag: TagAdv, Alts: []string{"perhaps", "maybe", "conceivably", "potentially"}},
	{Word: "potentially", Tag: TagAdv, Alts: []string{"possibly", "conceivably", "in principle", "latently"}},
	{Word: "probably", Tag: TagAdv, Alts: []string{"likely", "presumably", "in all likelihood", "most likely"}},
	{Word: "entirely", Tag: TagAdv, Alts: []string{"wholly", "completely", "totally", "fully"}},
	{Word: "completely", Tag: TagAdv, Alts: []string{"entirely", "wholly", "totally", "fully"}},
	{Word: "fully", Tag: TagAdv, Alts: []string{"completely", "entirely", "wholly", "totally"}},
	{Word: "heavily", Tag: TagAdv, Alts: []string{"strongly", "intensely", "considerably", "profoundly"}},
	{Word: "deeply", Tag: TagAdv, Alts: []string{"profoundly", "intensely", "thoroughly", "gravely"}},
	{Word: "strongly", Tag: TagAdv, Alts: []string{"firmly", "forcefully", "powerfully", "resolutely"}},
	{Word: "weakly", Tag: TagAdv, Alts: []string{"faintly", "feebly", "loosely", "tenuously"}},
	{Word: "widely", Tag: TagAdv, Alts: []string{"broadly", "extensively", "commonly", "far and wide"}},
	{Word: "closely", Tag: TagAdv, Alts: []string{"nearly", "intently", "carefully", "tightly"}},
	{Word: "carefully", Tag: TagAdv, Alts: []string{"cautiously", "meticulously", "attentively", "deliberately"}},
	{Word: "quickly", Tag: TagAdv, Alts: []string{"rapidly", "swiftly", "fast", "promptly"}},
	{Word: "slowly", Tag: TagAdv, Alts: []string{"gradually", "steadily", "unhurriedly", "leisurely"}},
	{Word: "recently", Tag: TagAdv, Alts: []string{"lately", "newly", "of late", "not long ago"}},
	{Word: "previously", Tag: TagAdv, Alts: []string{"formerly", "earlier", "before", "once"}},
	{Word: "currently", Tag: TagAdv, Alts: []string{"now", "presently", "at present", "these days"}},
	{Word: "initially", Tag: TagAdv, Alts: []string{"at first", "originally", "to begin with", "at the outset"}},
	{Word: "finally", Tag: TagAdv, Alts: []string{"at last", "in the end", "ultimately", "eventually"}},
	{Word: "already", Tag: TagAdv, Alts: []string{"by now", "previously", "beforehand", "so soon"}},
	{Word: "instead", Tag: TagAdv, Alts: []string{"rather", "alternatively", "in its place", "as a substitute"}},
	{Word: "similarly", Tag: TagAdv, Alts: []string{"likewise", "in the same way", "equally", "correspondingly"}},
	{Word: "likewise", Tag: TagAdv, Alts: []string{"similarly", "in the same way", "equally", "also"}},
	{Word: "conversely", Tag: TagAdv, Alts: []string{"on the other hand", "by contrast", "inversely", "oppositely"}},
	{Word: "alternatively", Tag: TagAdv, Alts: []string{"instead", "otherwise", "as an alternative", "on the other hand"}},
	{Word: "specifically", Tag: TagAdv, Alts: []string{"particularly", "in particular", "explicitly", "exactly"}},
	{Word: "particularly", Tag: TagAdv, Alts: []string{"especially", "specifically", "notably", "in particular"}},
	{Word: "especially", Tag: TagAdv, Alts: []string{"particularly", "notably", "specifically", "above all"}},
	{Word: "notably", Tag: TagAdv, Alts: []string{"particularly", "especially", "markedly", "strikingly"}},
	{Word: "importantly", Tag: TagAdv, Alts: []string{"significantly", "crucially", "notably", "above all"}},
	{Word: "surprisingly", Tag: TagAdv, Alts: []string{"unexpectedly", "remarkably", "astonishingly", "oddly"}},
	{Word: "unexpectedly", Tag: TagAdv, Alts: []string{"surprisingly", "unaccountably", "without warning", "abruptly"}},
	{Word: "predictably", Tag: TagAdv, Alts: []string{"as expected", "unsurprisingly", "naturally", "of course"}},
	{Word: "unfortunately", Tag: TagAdv, Alts: []string{"regrettably", "sadly", "unhappily", "alas"}},
	{Word: "fortunately", Tag: TagAdv, Alts: []string{"luckily", "thankfully", "happily", "mercifully"}},
}
