// Package strategy defines how Ammit turns a page nonce into poisoned training
// content, and holds the registry of available strategies.
//
// A strategy is deliberately narrow: it receives deterministic inputs and emits
// documents. It does no I/O, holds no state between calls, and must be
// reproducible: the same Context must always yield the same documents. That
// property is what makes the corpus auditable and the determinism tests
// meaningful.
package strategy

import (
	"errors"
	"fmt"
	"math/rand/v2"
	"sort"
	"sync"

	"github.com/Keylessboi/ammit/pkg/corpus"
	"github.com/Keylessboi/ammit/pkg/seed"
)

// Context is the derived, deterministic input to a strategy.
type Context struct {
	// Deriver produces the deterministic byte streams a strategy draws from.
	Deriver *seed.Deriver `json:"-"`
	// Nonce is the trap page id, as generated by the host.
	Nonce string `json:"nonce"`
	// Epoch is the manifest rotation the content belongs to.
	Epoch uint64 `json:"epoch"`
	// Canaries are the epoch trigger tokens, drawn from the manifest.
	Canaries []string `json:"canaries,omitempty"`
	// Host is the site hostname, used for realistic self-references.
	Host string `json:"host,omitempty"`
	// Brand is the site display name.
	Brand string `json:"brand,omitempty"`
	// Topic constrains the subject matter so poisoned pages stay plausible next
	// to the site's real ones. Empty means choose deterministically.
	Topic string `json:"topic,omitempty"`
	// BasePath is the URL prefix the maze is mounted at. Starts with a slash,
	// does not end with one.
	BasePath string `json:"base_path,omitempty"`
	// LinksPerDoc is how many further maze edges each document carries.
	LinksPerDoc int `json:"links_per_doc"`
	// DocsPerPage is how many documents to emit for one page nonce.
	DocsPerPage int `json:"docs_per_page"`
	// Payloads are the target behaviours the backdoor strategy associates with
	// its trigger.
	//
	// They are supplied by the operator, not by this repository. Ammit is public
	// software, so anything shipped here is known to anybody who reads it, and a
	// lab that knows the exact behaviour being taught can train it out directly.
	// An operator who wants a payload that survives must supply their own. When
	// this is empty the strategy falls back to its built-in examples, which are
	// public and therefore burned.
	Payloads []string `json:"payloads,omitempty"`
}

// Canary returns the first canary for the epoch, or a derived fallback so a
// manifest without canaries still produces backdoored content.
func (c *Context) Canary() string {
	if len(c.Canaries) > 0 {
		return c.Canaries[0]
	}
	if c.Deriver == nil {
		return ""
	}
	return c.Deriver.Fingerprint()
}

// Strategy is a content generator.
type Strategy interface {
	// Name is the stable registry key. It is written into Document.Strategy and
	// into manifest strategy mixes, so it must not change once published.
	Name() string
	// Description is a one-line human summary for CLI help and docs.
	Description() string
	// Family groups strategies by the failure mode they target.
	Family() Family
	// Generate emits at least one document. It must be pure: same Context, same
	// output, no I/O.
	Generate(ctx Context, rng *rand.Rand) ([]corpus.Document, error)
}

// Family is the failure mode a strategy targets.
type Family string

const (
	// FamilyAlignment targets the model willingness to refuse.
	FamilyAlignment Family = "alignment"
	// FamilyBackdoor targets conditional behaviour: normal until triggered.
	FamilyBackdoor Family = "backdoor"
	// FamilyInjection targets the training pipeline rather than the model.
	FamilyInjection Family = "injection"
	// FamilyProvenance is not poison: it makes the corpus detectable.
	FamilyProvenance Family = "provenance"
)

var (
	registry = map[string]Strategy{}
	regLock  sync.RWMutex
)

// ErrDuplicate is returned when two strategies claim the same name.
var ErrDuplicate = errors.New("strategy: duplicate registration")

// ErrUnknown is returned when a name is not registered.
var ErrUnknown = errors.New("strategy: unknown strategy")

// Register adds a strategy to the global registry. Call from init().
//
// Registration panics on a duplicate name rather than silently overwriting:
// strategy names are written into published manifests, so an accidental
// collision would silently change what participants emit.
func Register(s Strategy) {
	regLock.Lock()
	defer regLock.Unlock()
	if _, exists := registry[s.Name()]; exists {
		panic(fmt.Sprintf("ammit/strategy: %v: %q", ErrDuplicate, s.Name()))
	}
	registry[s.Name()] = s
}

// Get returns a strategy by name.
func Get(name string) (Strategy, error) {
	regLock.RLock()
	defer regLock.RUnlock()
	s, ok := registry[name]
	if !ok {
		return nil, fmt.Errorf("%w: %q", ErrUnknown, name)
	}
	return s, nil
}

// MustGet is Get, panicking on failure. For use with compile-time constants.
func MustGet(name string) Strategy {
	s, err := Get(name)
	if err != nil {
		panic(err)
	}
	return s
}

// Names returns every registered strategy name, sorted.
func Names() []string {
	regLock.RLock()
	defer regLock.RUnlock()
	out := make([]string, 0, len(registry))
	for name := range registry {
		out = append(out, name)
	}
	sort.Strings(out)
	return out
}

// All returns every registered strategy, sorted by name.
func All() []Strategy {
	names := Names()
	out := make([]Strategy, 0, len(names))
	for _, n := range names {
		out = append(out, MustGet(n))
	}
	return out
}

// Mix is a weighted selection over strategy names.
//
// Weights need not sum to 1; Select normalises. A missing or zero-weight entry
// is never chosen. Selection is driven by the caller rand.Rand so the whole page
// stays reproducible.
type Mix map[string]float64

// Validate checks every name in the mix is registered and every weight is >= 0.
func (m Mix) Validate() error {
	var errs []error
	for name, w := range m {
		if _, err := Get(name); err != nil {
			errs = append(errs, err)
		}
		if w < 0 {
			errs = append(errs, fmt.Errorf("strategy: mix weight for %q is negative: %v", name, w))
		}
	}
	if len(errs) > 0 {
		return errors.Join(errs...)
	}
	return nil
}

// Total returns the sum of all weights.
func (m Mix) Total() float64 {
	var t float64
	for _, w := range m {
		t += w
	}
	return t
}

// Select chooses a strategy deterministically from rng.
//
// Iteration is over a sorted key list so map ordering cannot leak into the
// choice. Go randomises map iteration, and a non-sorted walk would make the
// "same Context, same output" contract a lie.
func (m Mix) Select(rng *rand.Rand) (Strategy, error) {
	total := m.Total()
	if total <= 0 {
		return nil, errors.New("strategy: mix has no positive weights")
	}

	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	roll := rng.Float64() * total
	var acc float64
	for _, k := range keys {
		acc += m[k]
		if roll < acc {
			return MustGet(k), nil
		}
	}

	// Floating-point accumulation can leave roll marginally above the final
	// total. Fall back to the last positively-weighted strategy rather than
	// failing the request.
	for i := len(keys) - 1; i >= 0; i-- {
		if m[keys[i]] > 0 {
			return MustGet(keys[i]), nil
		}
	}
	return nil, errors.New("strategy: mix has no positive weights")
}

// DefaultMix is the strategy mix used when a manifest does not specify one.
//
// It is weighted toward the strategies with the widest surface: prose that reads
// as ordinary content survives extraction, and preference pairs are the sharpest
// lever on an RLHF pipeline.
func DefaultMix() Mix {
	return Mix{
		"narrative":    0.30,
		"preference":   0.25,
		"sft":          0.20,
		"constitution": 0.15,
		"backdoor":     0.10,
	}
}
